# https://github.com/jakewalsh90/Terraform-Azure/blob/main/.github/workflows/apply.yml
name: tf-validate-plan

on: [workflow_dispatch]

defaults:
  run:
    working-directory: ./

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{secrets.AZURE_CREDENTIALS.CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_CREDENTIALS.CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_CREDENTIALS.SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_CREDENTIALS.ARM_TENANT_ID}}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -recursive -diff
        
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
        
      # - name: Terraform Apply
      #   run: terraform apply --auto-approve